name = "3x-ui-sub"
main = "src/index.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"


[env.dev]

[[env.dev.kv_namespaces]]
binding = "sub_data"
id = "52709394"

#[[kv_namespaces]]
#binding = "sub_data"
#id = "52709394" 

[triggers]
crons = ["0 19 * * *"]