name = "3x-ui-sub"
main = "src/index.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"


[[kv_namespaces]]
binding = "sub_data"
id = "a591ef9134944b4f851502278da15ec9" 

[triggers]
crons = ["0 19 * * *"]